### ISSUE TITLE
fix layout of diff page.

### ISSUE THREAD

**Issue by Aha00a** [Aha00a/AhaWiki#29]
add style below

```css
.AhaWiki .diff .left, .AhaWiki .diff .right {
    word-break: break-all;
}
```
